---
title: "Correlations ICARS/SARA/mFARS"
author: "Christian Rummey"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: no
    number_sections: yes
  html_document:
    toc: yes
    df_print: paged
    number_sections: yes
editor_options:
  chunk_output_type: console
  markdown:
    wrap: 100
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=5, fig.align='center', echo=F, warning=F, message=F, cache=F)

library(corrr)
```

```{r prepare data, echo = F, message = F}

dt. <- readRDS('DATA derived/long.data.rds') %>%
  group_by(sjid, paramcd, amb) %>% 
  filter(avisitn == min(avisitn)) %>% 
  mutate(paramcd = factor(paramcd, c(
    'FARSn'  ,'mFARS','SARA','ICARS',
    'FARS.E' , 'SARA.ax' , 'ICARS.ax',
    'FARS.BC', 'SARA.ki', 'ICARS.ki', 
    'FARS.Am', 's4.speech', 'ICARS.sp'))) %>% 
  filter(forslope == 1) %>% 
  select(-c('forslope', 'int', 'chg', 'maxscore')) %>% 
  select(-time.) # has rounding issues, see 4208


dt.od <- dt. %>% 
  filter(paramcd %in% c('FARS.Am', 'ICARS.sp','s4.speech')) %>% 
  ungroup %>% 
  spread(paramcd, aval)


dt.ki <- dt. %>% 
  filter(paramcd %in% c('FARS.BC', 'ICARS.ki','SARA.ki')) %>% 
  spread(paramcd, aval)

dt.gp <- dt. %>% 
  filter(paramcd %in% c('FARS.E', 'ICARS.ax','SARA.ax')) %>% 
  spread(paramcd, aval)

dt. %<>% 
  filter(paramcd %in% c('FARSn','mFARS', 'ICARS','SARA')) %>% 
  spread(paramcd, aval)

```

```{r full scores}
tmp    <- dt. %>% select( sjid, age, mFARS, FARSn, SARA, ICARS) %>% mutate( type = 'scale' )
tmp2   <- dt. %>% select( sjid, age, mFARS, FARSn, SARA, ICARS) %>% mutate( type = 'pct'   ) %>% 
  mutate( mFARS = 100 * mFARS /93  ) %>% 
  mutate( FARSn = 100 * FARSn /125 ) %>% 
  mutate( SARA  = 100 * SARA  /40  ) %>% 
  mutate( ICARS = 100 * ICARS /100 )
tmp.od  <- dt.od %>% select(sjid, age, FARS.Am , s4.speech, ICARS.sp ) %>% mutate(type = 'scale')
tmp2.od  <- dt.od %>% select(sjid, age, FARS.Am , s4.speech, ICARS.sp ) %>% mutate(type = 'pct') %>% 
  mutate( FARS.Am = 100 * FARS.Am   /5 ) %>% 
  mutate( s4.speech  = 100 * s4.speech /6 ) %>% 
  mutate( ICARS.sp = 100 * ICARS.sp  /8 )
tmp.ki  <- dt.ki %>% select(sjid, age, FARS.BC, SARA.ki, ICARS.ki ) %>% mutate(type = 'scale')
tmp2.ki  <- dt.ki %>% select(sjid, age, FARS.BC, SARA.ki, ICARS.ki ) %>% mutate(type = 'pct'  ) %>% 
  mutate( FARS.BC  = 100 * FARS.BC  /52 ) %>% 
  mutate( SARA.ki  = 100 * SARA.ki  /16 ) %>% 
  mutate( ICARS.ki = 100 * ICARS.ki /52 )

tmp.ax  <- dt.gp %>% select(sjid, age, FARS.E , SARA.ax, ICARS.ax ) %>% mutate(type = 'scale')
tmp2.ax  <- dt.gp %>% select(sjid, age, FARS.E , SARA.ax, ICARS.ax ) %>% mutate(type = 'pct'  ) %>% 
  mutate( FARS.E   = 100 * FARS.E   /36 ) %>% 
  mutate( SARA.ax  = 100 * SARA.ax  /18 ) %>% 
  mutate( ICARS.ax = 100 * ICARS.ax /34 )

																																												  

											 

		   

																																   
																																		
																											  
																					

																																					 
																				
																		   



	  
																					   
																						  
									 
									 
								

scores. <- bind_rows(
  tmp  %>% rename(score = mFARS) %>% mutate(dep = 'mFARS') %>% gather(indep, value, SARA, ICARS, FARSn),
  tmp  %>% rename(score = FARSn) %>% mutate(dep = 'FARSn') %>% gather(indep, value, SARA, ICARS, mFARS),
  tmp  %>% rename(score = SARA ) %>% mutate(dep = 'SARA' ) %>% gather(indep, value, mFARS, ICARS, FARSn),
  tmp  %>% rename(score = ICARS) %>% mutate(dep = 'ICARS') %>% gather(indep, value, mFARS, SARA, FARSn),
  tmp2 %>% rename(score = mFARS) %>% mutate(dep = 'mFARS') %>% gather(indep, value, SARA, ICARS, FARSn),
  tmp2 %>% rename(score = FARSn) %>% mutate(dep = 'FARSn') %>% gather(indep, value, SARA, ICARS, mFARS),
  tmp2 %>% rename(score = SARA ) %>% mutate(dep = 'SARA' ) %>% gather(indep, value, mFARS, ICARS, FARSn),
  tmp2 %>% rename(score = ICARS) %>% mutate(dep = 'ICARS') %>% gather(indep, value, mFARS, SARA, FARSn),
  tmp.od %>% rename(score = FARS.Am   ) %>% mutate(dep = 'FARS.Am'  ) %>% gather(indep, value, s4.speech, ICARS.sp),
  tmp.od %>% rename(score = s4.speech ) %>% mutate(dep = 's4.speech') %>% gather(indep, value, FARS.Am , ICARS.sp),
  tmp.od %>% rename(score = ICARS.sp  ) %>% mutate(dep = 'ICARS.sp' ) %>% gather(indep, value, s4.speech , FARS.Am),
  tmp2.od %>% rename(score = FARS.Am   ) %>% mutate(dep = 'FARS.Am'  ) %>% gather(indep, value, s4.speech, ICARS.sp),
  tmp2.od %>% rename(score = s4.speech ) %>% mutate(dep = 's4.speech') %>% gather(indep, value, FARS.Am , ICARS.sp),
  tmp2.od %>% rename(score = ICARS.sp  ) %>% mutate(dep = 'ICARS.sp' ) %>% gather(indep, value, s4.speech , FARS.Am),
  tmp.ax %>% rename(score = FARS.E  ) %>% mutate(dep = 'FARS.E'  ) %>% gather(indep, value, SARA.ax, ICARS.ax),
  tmp.ax %>% rename(score = SARA.ax ) %>% mutate(dep = 'SARA.ax' ) %>% gather(indep, value, FARS.E , ICARS.ax),
  tmp.ax %>% rename(score = ICARS.ax) %>% mutate(dep = 'ICARS.ax') %>% gather(indep, value, SARA.ax , FARS.E),
  tmp2.ax %>% rename(score = FARS.E  ) %>% mutate(dep = 'FARS.E'  ) %>% gather(indep, value, SARA.ax, ICARS.ax),
  tmp2.ax %>% rename(score = SARA.ax ) %>% mutate(dep = 'SARA.ax' ) %>% gather(indep, value, FARS.E , ICARS.ax),
  tmp2.ax %>% rename(score = ICARS.ax) %>% mutate(dep = 'ICARS.ax') %>% gather(indep, value, SARA.ax , FARS.E),
  tmp.ki %>% rename(score = FARS.BC  ) %>% mutate(dep = 'FARS.BC'  ) %>% gather(indep, value, SARA.ki, ICARS.ki),
  tmp.ki %>% rename(score = SARA.ki ) %>% mutate(dep = 'SARA.ki' ) %>% gather(indep, value, FARS.BC , ICARS.ki),
  tmp.ki %>% rename(score = ICARS.ki) %>% mutate(dep = 'ICARS.ki') %>% gather(indep, value, SARA.ki , FARS.BC),
  tmp2.ki %>% rename(score = FARS.BC  ) %>% mutate(dep = 'FARS.BC'  ) %>% gather(indep, value, SARA.ki, ICARS.ki),
  tmp2.ki %>% rename(score = SARA.ki ) %>% mutate(dep = 'SARA.ki' ) %>% gather(indep, value, FARS.BC , ICARS.ki),
  tmp2.ki %>% rename(score = ICARS.ki) %>% mutate(dep = 'ICARS.ki') %>% gather(indep, value, SARA.ki , FARS.BC)
) 

table <- scores. %>% 
  group_by(type, dep, indep) %>% 
  nest() %>% 
  mutate ( lm.mod = map( data  , ~ lm (score ~ value, data = .))) %>% 
  mutate ( coef   = map( lm.mod, ~ broom::tidy (.))) %>% 
  unnest ( coef ) %>% 
  select ( dep, indep, term, estimate) %>% 
  spread ( term, estimate ) %>% 
  rename ( intercept = `(Intercept)`, slope = value ) %>% 
  mutate ( dep   = factor(dep, c('mFARS', 'FARSn','SARA', 'ICARS', 'FARS.E', 'SARA.ax', 'ICARS.ax', 'FARS.BC', 'SARA.ki', 'ICARS.ki', 'FARS.Am', 's4.speech', 'ICARS.sp'))) %>% 
  mutate ( indep = factor(indep, c('mFARS', 'FARSn', 'SARA', 'ICARS', 'FARS.E', 'SARA.ax', 'ICARS.ax', 'FARS.BC', 'SARA.ki', 'ICARS.ki', 'FARS.Am', 's4.speech', 'ICARS.sp'))) %>% 
  arrange( type, dep, indep) %>% 
  pivot_wider(id_cols = c('dep', 'indep'), names_from = c('type'), values_from = c('intercept', 'slope') ) %>% 
  select(dep, indep, intercept_scale, slope_scale, intercept_pct, slope_pct) 

table %>%
  # filter(!((dep == 'SARA' | dep == 'ICARS') & indep == 'FARSn')) %>% 
  flextable() %>% 
  colformat_double(digits = 2) %>% 
  set_header_labels(values = list(dep = '', indep = 'predicted from', 
                                  intercept_scale = 'intercept',
                                  slope_scale     = 'slope',
                                  intercept_pct   = 'intercept',
                                  slope_pct   = 'slope')) %>% 
  add_header_row(values = c('','Points','%'), colwidths = c(2, 2, 2)) %>% 
  align(j = c(1:6), part = 'all', align = 'center'  ) %>% 
  hline(i = c(3, 6,9,12,14,16,18,20,22,24)) %>% 
  set_caption("Conversion Coefficients for full Scales",
              autonum = run_autonum(seq_id = "tab", bkm = "full"))

table %>% 
  saveRDS('DATA derived/coefficients.rds')

```

```{r early scores}

table2 <- scores. %>% 
  mutate(threshold = ifelse(indep == 'SARA', 9, ifelse(indep == 'ICARS', 23, ifelse(indep == 'mFARS', 21, ifelse(indep == 'FARSn', 24, NA))))) %>% 
  filter(value<threshold) %>% 
  group_by(type, dep, indep, threshold) %>% 
  nest() %>% 
  mutate ( lm.mod = map( data  , ~ lm (score ~ value, data = .))) %>% 
  mutate ( coef   = map( lm.mod, ~ broom::tidy (.))) %>% 
  unnest ( coef ) %>% 
  select ( dep, indep, threshold, term, estimate) %>% 
  spread ( term, estimate ) %>% 
  rename ( intercept = `(Intercept)`, slope = value ) %>% 
  mutate ( dep   = factor(dep, c('mFARS', 'FARSn','SARA', 'ICARS'))) %>% 
  mutate ( indep = factor(indep, c('mFARS', 'FARSn', 'SARA', 'ICARS'))) %>% 
  arrange( type, dep, indep) %>% 
  pivot_wider(id_cols = c('dep', 'indep','threshold'), names_from = c('type'), values_from = c('intercept', 'slope') ) %>% 
  select(dep, indep, threshold, intercept_scale, slope_scale, intercept_pct, slope_pct) 

table2 %>%
  filter(!((dep == 'SARA' | dep == 'ICARS') & indep == 'FARSn')) %>% 
  flextable() %>% 
  colformat_double(digits = 2) %>% 
  set_header_labels(values = list(dep = '', indep = 'predicted from', 
                                  intercept_scale = 'intercept',
                                  slope_scale     = 'slope',
                                  intercept_pct   = 'intercept',
                                  slope_pct   = 'slope')) %>% 
  add_header_row(values = c('','Points','%'), colwidths = c(3, 2, 2)) %>% 
  align(j = c(1:6), part = 'all', align = 'center'  ) %>% 
  hline(i = c(3, 5)) %>% 
  set_caption("Conversion Coefficients for lower End of the Scales (early patients)",
              autonum = run_autonum(seq_id = "tab", bkm = "full"))
```
