---
title: "Correlations ICARS/SARA/mFARS"
author: "Christian Rummey"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    df_print: paged
    number_sections: yes
  word_document:
    toc: yes
    number_sections: yes
editor_options:
  chunk_output_type: inline
  markdown:
    wrap: 100
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8.5, fig.height=5.5, fig.align='center', echo=F, warning=F, message=F, cache=F)
```

```{r, echo = F, message = F}
library(corrr)
require(lme4)
require(lmerTest)
require(optimx)
require(broom.mixed)

.lme4.ctrl      <- lmerControl( 
  optimizer = "optimx", 
  calc.derivs = FALSE, 
  optCtrl = list(method = "L-BFGS-B" , 
                 starttests = FALSE, 
                 kkt = FALSE, 
                 # maxiter = 10000, 
                 save.failures = T)) # def iterations 500

dt. <- readRDS('DATA derived/long.data.rds') %>% 
  mutate(paramcd = factor(paramcd, c('mFARS','SARA','ICARS','FARS.E','SARA.ax','ICARS.gp','FARS.B', 'SARA.ki', 'ICARS.ki')))

dt.ki <- dt. %>% 
  filter(paramcd %in% c('FARS.B', 'ICARS.ki','SARA.ki')) %>% 
  spread(paramcd, aval)

dt.gp <- dt. %>% 
  filter(paramcd %in% c('FARS.E', 'ICARS.gp','SARA.ax')) %>% 
  spread(paramcd, aval)

dt. %<>% 
  filter(paramcd %in% c('mFARS', 'ICARS','SARA')) %>% 
  spread(paramcd, aval)


dt.all <- bind_rows( 
  dt. %>% mutate(dep = 'mFARS') %>% rename(score = mFARS) %>% gather(paramcd, aval, SARA , ICARS), 
  dt. %>% mutate(dep = 'SARA' ) %>% rename(score = SARA ) %>% gather(paramcd, aval, mFARS, ICARS), 
  dt. %>% mutate(dep = 'ICARS') %>% rename(score = ICARS) %>% gather(paramcd, aval, SARA , mFARS)
)

dt.l.gp <- bind_rows( 
  dt.gp %>% mutate(dep = 'FARS.E')   %>% rename(score = FARS.E  ) %>% gather(paramcd, aval, SARA.ax , ICARS.gp), 
  dt.gp %>% mutate(dep = 'SARA.ax' ) %>% rename(score = SARA.ax ) %>% gather(paramcd, aval, FARS.E  , ICARS.gp), 
  dt.gp %>% mutate(dep = 'ICARS.gp') %>% rename(score = ICARS.gp) %>% gather(paramcd, aval, SARA.ax , FARS.E)
)

dt.l.ki <- bind_rows( 
  dt.ki %>% mutate(dep = 'FARS.B')   %>% rename(score = FARS.B   ) %>% gather(paramcd, aval, SARA.ki , ICARS.ki), 
  dt.ki %>% mutate(dep = 'SARA.ki' ) %>% rename(score = SARA.ki  ) %>% gather(paramcd, aval, FARS.B, ICARS.ki), 
  dt.ki %>% mutate(dep = 'ICARS.ki') %>% rename(score = ICARS.ki ) %>% gather(paramcd, aval, SARA.ki , FARS.B)
)


```
# Full Output tables

## Total Scores

```{r}
coef.lm <- dt.all %>% 
  group_by(dep, paramcd) %>% nest() %>% 
  mutate( lm.mod = map(data , ~ lm( score ~ aval, data = . ))) %>% 
  mutate( coefs = map(lm.mod, ~ broom::tidy ( .x, conf.int = T ))) %>% 
  unnest( coefs) %>% arrange(term)%>% mutate(model = 'lm')

coef.lmer <- dt.all %>% 
  group_by(dep, paramcd) %>% 
  nest() %>% 
  mutate( lmer.mod = map(data , ~ lmer( score ~ aval + (1|sjid) , data = . , control = .lme4.ctrl ))) %>% 
  mutate( coefs = map(lmer.mod, ~ broom::tidy ( .x, effects = 'fixed', conf.int = T ))) %>% 
  unnest( coefs) %>% arrange(term) %>% 
  mutate( model = 'MMRM')

coefs <- coef.lm %>% 
  bind_rows(coef.lmer) %>% 
  mutate(dep   = factor(dep, c('mFARS', 'SARA', 'ICARS'))) %>% 
  mutate(indep = factor(paramcd, c('mFARS', 'SARA', 'ICARS'))) %>% 
  ungroup %>% 
  select(model, dep, indep, term, estimate, conf.low, conf.high, p.value) %>% 
  arrange(dep, indep, model)

coefs %>% 
  .fixmod() %>% 
  flextable %>%
  colformat_double() %>% 
  colformat_double(j = 5, digits = 2) %>% 
  flextable::hline(i = seq(4, nrow(coefs), 4))

```

## Axial Function

```{r}
coef.lm <- dt.l.gp %>% 
  group_by(dep, paramcd) %>% nest() %>% 
  mutate( lm.mod = map(data , ~ lm( score ~ aval, data = . ))) %>% 
  mutate( coefs = map(lm.mod, ~ broom::tidy ( .x, conf.int = T ))) %>% 
  unnest( coefs) %>% arrange(term)%>% mutate(model = 'lm')

coef.lmer <- dt.l.gp %>% 
  group_by(dep, paramcd) %>% 
  nest() %>% 
  mutate( lmer.mod = map(data , ~ lmer( score ~ aval + (1|sjid) , data = . , control = .lme4.ctrl ))) %>% 
  mutate( coefs = map(lmer.mod, ~ broom::tidy ( .x, effects = 'fixed', conf.int = T ))) %>% 
  unnest( coefs) %>% arrange(term) %>% 
  mutate( model = 'MMRM')

coefs <- coef.lm %>% 
  bind_rows(coef.lmer) %>% 
  mutate(dep   = factor(dep, c('FARS.E', 'SARA.ax', 'ICARS.gp'))) %>% 
  mutate(indep = factor(paramcd, c('FARS.E', 'SARA.ax', 'ICARS.gp'))) %>% 
  ungroup %>% 
  select(model, dep, indep, term, estimate, conf.low, conf.high, p.value) %>% 
  arrange(dep, indep, model)

coefs %>% flextable %>% colformat_double() %>% flextable::hline(i = seq(4, nrow(coefs), 4))

```

## Kinetic function

```{r}
coef.lm <- dt.l.ki %>% 
  group_by(dep, paramcd) %>% nest() %>% 
  mutate( lm.mod = map(data , ~ lm( score ~ aval, data = . ))) %>% 
  mutate( coefs = map(lm.mod, ~ broom::tidy ( .x, conf.int = T ))) %>% 
  unnest( coefs) %>% arrange(term)%>% mutate(model = 'lm')

coef.lmer <- dt.l.ki %>% 
  group_by(dep, paramcd) %>% 
  nest() %>% 
  mutate( lmer.mod = map(data , ~ lmer( score ~ aval + (1|sjid) , data = . , control = .lme4.ctrl ))) %>% 
  mutate( coefs = map(lmer.mod, ~ broom::tidy ( .x, effects = 'fixed', conf.int = T ))) %>% 
  unnest( coefs) %>% arrange(term) %>% 
  mutate( model = 'MMRM')

coefs <- coef.lm %>% 
  bind_rows(coef.lmer) %>% 
  mutate(dep   = factor(dep, c('FARS.B', 'SARA.ki', 'ICARS.ki'))) %>% 
  mutate(indep = factor(paramcd, c('FARS.B', 'SARA.ki', 'ICARS.ki'))) %>% 
  ungroup %>% 
  select(model, dep, indep, term, estimate, conf.low, conf.high, p.value) %>% 
  arrange(dep, indep, model)

coefs %>% flextable %>% colformat_double() %>% flextable::hline(i = seq(4, nrow(coefs), 4))

```
